### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by robert-stevens** [jackrobertscott/graphql-api-demo#4]
Hi,

I cloned the repo and ran npm install, during which I get this error:

> npm ERR! code E404
> npm ERR! 404 Not Found: flatmap-stream@https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.0.tgz

Not sure how to get pass it?

Thanks.

**Comment by Sashley** [comment]
Hi Jack,

Have some issues with

> npm install

 returning the following. Seems to be something missing.
(would really like it check it out, as can relate to your introduction).

TIA and Cheers,

[aa_2019-03-22T08_34_40_908Z-debug.log](https://github.com/jackrobertscott/graphql-api-demo/files/2995663/aa_2019-03-22T08_34_40_908Z-debug.log)

**Comment by larryhudson** [comment]
I got it to work by deleting package-lock.json and running 'npm install' again.

**Comment by vitorpiovezam** [comment]
> I got it to work by deleting package-lock.json and running 'npm install' again.

This works, but the start script is wrong, run a non-existing file in a non-existing folder.

**Comment by jackrobertscott** [comment]
I deleted package-lock.json - this should fix the problem 😅
